language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3

matrix:
    include:
        - php: 5.5
          dist: trusty

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
    - composer update

script:
  - ./vendor/bin/phpunit
