language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - hhvm

before_script:
    - "composer require --dev phpspec/phpspec:~2.0 --no-update"
    - "composer install --dev"

script: vendor/bin/phpspec run -v -f p
